In [46]:
import numpy as np
N = 10
x = np.arange(0, N)
reverse_x = x[::-1] #Обратный массив
reverse_x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [47]:
diag_x = np.diag(reverse_x) #Диагональная матрица
diag_x

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [48]:
np.sum(diag_x)
"""
Т.к. матрица диагональная, можно просто сложить все элементы
"""

45

In [60]:
from numpy import linalg
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
c = linalg.solve(a, b)
c

array([ 0.46666667,  3.84444444, -5.55555556])

In [59]:
np.dot(a, c) #Проверка

array([ 4., 12., -3.])

In [62]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [158]:
cos = [] #В пустой список буду записывать значения косинусов
next_user_stats_lenght = np.linalg.norm(next_user_stats)
for i in users_stats:
    users_stats_lenght = np.linalg.norm(i)
    a = np.dot(i, next_user_stats) / (users_stats_lenght * next_user_stats_lenght)
    cos.append(a)
print('Самый похожий пользователь это №', cos.index(max(cos)) + 1) #Нумерация идет с 0

Самый похожий пользователь это № 8


In [165]:
"""
Можно ли результат вычислений а каким-то образом записывать в пустой массив и потом использовать функцию argmax?
"""

'\nМожно ли результат вычислений а каким-то образом записывать в пустой массив и потом использовать функцию argmax?\n'